# Generated by Django 3.1.5 on 2021-01-22 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('text', models.CharField(max_length=500)),
                ('emotions', models.CharField(max_length=700)),
                ('before', models.CharField(max_length=100)),
                ('after', models.CharField(max_length=100)),
                ('prolific', models.CharField(default='0000000', max_length=100)),
            ],
        ),
    ]
